blog/urls.py
from django.urls import path, include
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.blog, name='blog'),
    path('<int:pk>/', views.blog_detail, name='blog-detail'),

]

home/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home, name='nav-bar'),
]

zes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('home.urls')),
    path('blog/', include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Navigation(models.Model):
    logo = models.ImageField(upload_to='logo')
    is_active = models.BooleanField(unique=True, blank=True)


class BlogHead(models.Model):
    title = models.CharField(max_length=100)
    background_image = models.ImageField(default='default.jpg', upload_to='blog-background')
    is_active = models.BooleanField(unique=True, blank=True)


class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    blog_title = models.CharField(max_length=100)
    blog_sub_title = models.CharField(max_length=100, blank=True)
    blog_image = models.ImageField(upload_to='blog')
    description = RichTextField()
    date_published = models.DateTimeField(auto_now_add=True)
    blog_category = models.CharField(max_length=50)


class FooterContact(models.Model):
    address = models.CharField(max_length=100)
    phone = models.IntegerField()
    email = models.EmailField()
    is_valid = models.BooleanField(unique=True, blank=True)

home/models.py
from django.db import models


class Home(models.Model):
    logo = models.ImageField(upload_to='logo')
    background_image = models.ImageField(upload_to='background-image')
    head = models.CharField(max_length=150)
    sub_head = models.CharField(max_length=150)
    next_sub_head = models.CharField(max_length=150)

    def __str__(self):
        return self.head

blog/views.py
from django.shortcuts import render
from .models import Blog, Navigation, BlogHead, FooterContact
from django.core.paginator import Paginator


def blog(request):
    logo = Navigation.objects.all()
    blog_head = BlogHead.objects.all()
    contact = FooterContact.objects.all()
    blog = Blog.objects.order_by('-date_published')
    paginator = Paginator(blog, 4, orphans=1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'blog/blog-grid-2-sidebar.html',
                  {'logo': logo, 'blog': page_obj, 'blog_head': blog_head, 'contact': contact})


def blog_detail(request, pk):
    logo = Navigation.objects.all()
    blog_detail = Blog.objects.get(id=pk)
    contact = FooterContact.objects.all()
    return render(request, 'blog/blog-detail.html', {'sug': blog_detail, 'logo':logo, 'contact': contact, 'arrange': True})

home/views.py
from .models import Home
from django.shortcuts import render


def home(request):
    home = Home.objects.all()
    return render(request, 'home.html', {'image': home})

blog/templates/blog/blog-detail.html
{% extends 'base.html' %}
{% block content %}

<!-- contact area -->
<div class="content-area">
    <div class="container max-w900">
        <!-- blog start -->
        <div class="blog-post blog-single">
            <div class="post-title ">
                <h4 class="post-title fw5"><a href="#">{{sug.blog_title}}</a></h4>
            </div>
            <div class="post-meta m-b20">
                <ul>
                    <li class="post-date"><span>{{sug.date_published}}</span></li>
                    <li class="post-author">By <a href="#">{{sug.author}}</a></li>
                    <li class="post-comment"><a href="#">0 Comments</a></li>
                </ul>
            </div>
            <div class="post-media img-effect zoom-slow"><a href="#"><img src="{{sug.blog_image.url}}"
                                                                          alt=""></a>
                <ul class="blog-categories">
                    <li><a href="#">{{sug.blog_category}}</a></li>

                </ul>
            </div>
            <div class="post-text">
                <p>{{sug.description|safe}}</p>
                <div class="share-details-btn">
                    <ul>
                        <li><h5 class="m-a0">Share Post</h5></li>
                        <li><a href="#" class="site-button facebook button-sm"><i class="fa fa-facebook"></i>
                            Facebook</a></li>
                        <li><a href="#" class="site-button google-plus button-sm"><i class="fa fa-google-plus"></i>
                            Google Plus</a></li>
                        <li><a href="#" class="site-button linkedin button-sm"><i class="fa fa-linkedin"></i>
                            Linkedin</a></li>
                        <li><a href="#" class="site-button instagram button-sm"><i class="fa fa-instagram"></i>
                            Instagram</a></li>
                        <li><a href="#" class="site-button twitter button-sm"><i class="fa fa-twitter"></i> Twitter</a>
                        </li>
                        <li><a href="#" class="site-button whatsapp button-sm"><i class="fa fa-whatsapp"></i>
                            Whatsapp</a></li>
                    </ul>
                </div>
            </div>
            <div class="clear" id="comment-list">
                <div class="comments-area" id="comments">
                    <h2 class="comments-title">0 Comments</h2>
                    <div class="clearfix">
                        <!-- comment list END -->
                        <ol class="comment-list">
                            <li class="comment">
                                <div class="comment-body">
                                    <div class="comment-author vcard"><img class="avatar photo"
                                                                           src="images/testimonials/pic1.jpg"
                                                                           alt=""> <cite class="fn">Stacy poe</cite>
                                        <span class="says">says:</span></div>
                                    <div class="comment-meta"><a href="#">October 6, 2015 at 7:15 am</a></div>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae
                                        neqnsectetur adipiscing elit. Nam viae neqnsectetur adipiscing elit.
                                        Nam vitae neque vitae sapien malesuada aliquet. </p>
                                    <div class="reply"><a href="#" class="comment-reply-link">Reply</a></div>
                                </div>
                                <ol class="children">
                                    <li class="comment odd parent">
                                        <div class="comment-body">
                                            <div class="comment-author vcard"><img class="avatar photo"
                                                                                   src="images/testimonials/pic2.jpg"
                                                                                   alt=""> <cite class="fn">Stacy
                                                poe</cite> <span class="says">says:</span></div>
                                            <div class="comment-meta"><a href="#">October 6, 2015 at 7:15 am</a>
                                            </div>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae
                                                neque vitae sapien malesuada aliquet.
                                                In viverra dictum justo in vehicula. Fusce et massa eu ante ornare
                                                molestie. Sed vestibulum sem felis,
                                                ac elementum ligula blandit ac.</p>
                                            <div class="reply"><a href="#" class="comment-reply-link">Reply</a>
                                            </div>
                                        </div>
                                        <ol class="children">
                                            <li class="comment odd parent">
                                                <div class="comment-body">
                                                    <div class="comment-author vcard"><img class="avatar photo"
                                                                                           src="images/testimonials/pic3.jpg"
                                                                                           alt=""> <cite class="fn">Stacy
                                                        poe</cite> <span class="says">says:</span></div>
                                                    <div class="comment-meta"><a href="#">October 6, 2015 at 7:15
                                                        am</a></div>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
                                                        vitae neque vitae sapien malesuada aliquet.
                                                        In viverra dictum justo in vehicula. Fusce et massa eu ante
                                                        ornare molestie. Sed vestibulum sem felis,
                                                        ac elementum ligula blandit ac.</p>
                                                    <div class="reply"><a href="#"
                                                                          class="comment-reply-link">Reply</a></div>
                                                </div>
                                            </li>
                                        </ol>
                                        <!-- list END -->
                                    </li>
                                </ol>
                                <!-- list END -->
                            </li>
                            <li class="comment">
                                <div class="comment-body">
                                    <div class="comment-author vcard"><img class="avatar photo"
                                                                           src="images/testimonials/pic1.jpg"
                                                                           alt=""> <cite class="fn">Stacy poe</cite>
                                        <span class="says">says:</span></div>
                                    <div class="comment-meta"><a href="#">October 6, 2015 at 7:15 am</a></div>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae neque
                                        vitae sapien malesuada aliquet.
                                        In viverra dictum justo in vehicula. Fusce et massa eu ante ornare molestie.
                                        Sed vestibulum sem felis,
                                        ac elementum ligula blandit ac.</p>
                                    <div class="reply"><a href="#" class="comment-reply-link">Reply</a></div>
                                </div>
                            </li>
                            <li class="comment">
                                <div class="comment-body">
                                    <div class="comment-author vcard"><img class="avatar photo"
                                                                           src="images/testimonials/pic2.jpg"
                                                                           alt=""> <cite class="fn">Stacy poe</cite>
                                        <span class="says">says:</span></div>
                                    <div class="comment-meta"><a href="#">October 6, 2015 at 7:15 am</a></div>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae neque
                                        vitae sapien malesuada aliquet.
                                        In viverra dictum justo in vehicula. Fusce et massa eu ante ornare molestie.
                                        Sed vestibulum sem felis,
                                        ac elementum ligula blandit ac.</p>
                                    <div class="reply"><a href="#" class="comment-reply-link">Reply</a></div>
                                </div>
                            </li>
                            <li class="comment">
                                <div class="comment-body">
                                    <div class="comment-author vcard"><img class="avatar photo"
                                                                           src="images/testimonials/pic3.jpg"
                                                                           alt=""> <cite class="fn">Stacy poe</cite>
                                        <span class="says">says:</span></div>
                                    <div class="comment-meta"><a href="#">October 6, 2015 at 7:15 am</a></div>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae neque
                                        vitae sapien malesuada aliquet.
                                        In viverra dictum justo in vehicula. Fusce et massa eu ante ornare molestie.
                                        Sed vestibulum sem felis,
                                        ac elementum ligula blandit ac.</p>
                                    <div class="reply"><a href="#" class="comment-reply-link">Reply</a></div>
                                </div>
                            </li>
                        </ol>
                        <!-- comment list END -->
                        <!-- Form -->
                        <div class="comment-respond" id="respond">
                            <h4 class="comment-reply-title" id="reply-title">Leave a Reply <small> <a
                                    style="display:none;" href="#" id="cancel-comment-reply-link" rel="nofollow">Cancel
                                reply</a> </small></h4>
                            <form class="comment-form" id="commentform" method="post"
                                  action="http://sedatelab.com/developer/donate/wp-comments-post.php">
                                <p class="comment-form-author">
                                    <label for="author">Name <span class="required">*</span></label>
                                    <input type="text" value="author" name="author" placeholder="Author"
                                           id="author">
                                </p>
                                <p class="comment-form-email">
                                    <label for="email">Email <span class="required">*</span></label>
                                    <input type="text" value="email" placeholder="Email" name="email" id="email">
                                </p>
                                <p class="comment-form-url">
                                    <label for="url">Website</label>
                                    <input type="text" value="url" placeholder="Website" name="url" id="url">
                                </p>
                                <p class="comment-form-comment">
                                    <label for="comment">Comment</label>
                                    <textarea rows="8" name="comment" placeholder="Comment" id="comment"></textarea>
                                </p>
                                <p class="form-submit">
                                    <input type="submit" value="Post Comment" class="submit" id="submit"
                                           name="submit">
                                </p>
                            </form>
                        </div>
                        <!-- Form END -->
                    </div>
                </div>
            </div>
            <!-- blog END -->
        </div>
    </div>
</div>
<!-- Content END-->
{% endblock %}

blog/templates/blog/blog-grid-2-sidebar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="page-wraper">
    <div id="loading-area"></div>
    <!-- Content -->
    <div class="page-content bg-white">
        <!-- inner page banner -->
        {% for head in blog_head %}
        {% if head.is_active %}
        <div class="bnr-inr bg-pt" style="background-image:url({{head.background_image.url}});">
            <div class="container">
                <div class="bnr-inr-entry">
                    <h1>{{head.title}}</h1>
                    <!--Breadcrumb row-->
                    <div class="breadcrumb-row">
                        <ul class="list-inline">
                            <li><a href="">Home</a></li>
                            <li>Blog</li>
                        </ul>
                    </div>
                    <!-- Breadcrumb row END -->
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        <!-- inner page banner END -->
        <div class="content-area">
            <div class="container">
                <div class="row">
                    <!-- left part start -->
                    <div class="col-lg-9 col-md-7">
                        <div class="row">
                            <!-- blog grid  -->
                            <div id="masonry" class="blog-grid-2">

                                {% for blog in blog %}
                                <div class="post card-container col-lg-6 col-md-12 col-sm-12 mb-4">
                                    <div class="blog-grid blog-rounded theme-blog">
                                        <div class="post-media img-effect "><a
                                                href="{% url 'blog:blog-detail' blog.pk %}">
                                            <img src="{{blog.blog_image.url}}" alt=""></a>
                                            <ul class="blog-categories">
                                                <li><a href="#">{{blog.blog_category}}</a></li>

                                            </ul>
                                        </div>
                                        <div class="info p-tb20">
                                            <div class="post-title ">

                                                <h4 class="post-title fw5"><a
                                                        href="{% url 'blog:blog-detail' blog.pk %}">{{blog.blog_title}}</a>
                                                </h4>
                                            </div>
                                            <div class="post-meta">
                                                <ul>
                                                    <li class="post-date">{{blog.date_published}}</li>
                                                    <li class="post-author">By <a href="#">{{blog.author}}</a></li>
                                                    <li class="post-comment"><a href="#">0 Comments</a></li>
                                                </ul>
                                            </div>
                                            <div class="post-text">
                                                <p>{{blog.description|safe|slice:"300"}}..</p>
                                            </div>
                                            <div class="post-readmore blog-share">
                                                <a href="{% url 'blog:blog-detail' blog.pk %}" title="Read More"
                                                   rel="bookmark"
                                                   class="site-button-link border-link sharp">Read More
                                                    <i class="fa fa-angle-double-right"></i>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}


                            </div>
                            <!-- blog grid END -->
                            <!-- Pagination start -->
                            <div class="pagination-bx clearfix text-center col-md-12">
                                <ul class="pagination">
                                    {% if blog.has_previous %}
                                    <li class=""><a href="?page=1">1</a></li>
                                    <li class="previous"><a href="?page={{blog.previous_page_number}}"><i
                                            class="ti-arrow-left"></i> Prev</a></li>
                                    {% endif %}

                                    {% for num in blog.paginator.page_range %}
                                    {% if blog.number == num %}
                                    <li class="active"><a href="?page={{num}}">{{num}}</a></li>
                                    {% elif num > blog.number|add:'-3' and blog.number|add:'3' %}
                                    <li class=""><a href="?page={{num}}">{{num}}</a></li>
                                    {% endif %}
                                    {% endfor %}

                                    {% if blog.has_next %}

                                    <li class="next"><a href="?page={{blog.next_page_number}}">Next <i
                                            class="fa fa-angle-double-right"></i></a></li>
                                    {% endif %}


                                </ul>
                            </div>
                            <!-- Pagination END -->
                        </div>
                    </div>
                    <!-- left part start -->
                    <!-- Side bar start -->
                    <div class="col-lg-3 col-md-5 sticky-top">
                        <aside class="side-bar">
                            <div class="widget">
                                <h6 class="widget-title style-1">Search</h6>
                                <div class="search-bx style-1">
                                    <form role="search" method="post">
                                        <div class="input-group">
                                            <input name="text" class="form-control" placeholder="Enter your keywords..."
                                                   type="text">
                                            <span class="input-group-btn">
												<button type="submit" class="fa fa-search text-primary"></button>
                                            </span>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="widget recent-posts-entry">
                                <h6 class="widget-title style-1">Recent Posts</h6>
                                <div class="widget-post-bx">
                                    {% for blog in blog %}
                                    <div class="widget-post clearfix">
                                        <div class="post-media"><img
                                                src="{{blog.blog_image.url}}" width="200"
                                                height="143" alt=""></div>
                                        <div class="post-info">
                                            <div class="post-header">
                                                <h6 class="post-title"><a href="#">{{blog.blog_title}}</a></h6>
                                            </div>
                                            <div class="post-meta">
                                                <ul>
                                                    <li class="post-author">{{blog.author}}</li>
                                                    <li class="post-comment"><i class="ti-comment-alt"></i> 28</li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>

                            <div class="widget widget-newslatter">
                                <h6 class="widget-title style-1">Newsletter</h6>
                                <div class="news-box">
                                    <p>Enter your e-mail and subscribe to our newsletter.</p>
                                    <form class="dazSubscribe" action="script/mailchamp.php" method="post">
                                        <div class="dazSubscribeMsg"></div>
                                        <div class="input-group">
                                            <input name="dzEmail" required="required" type="email" class="form-control"
                                                   placeholder="Your Email"/>
                                            <button name="submit" value="Submit" type="submit"
                                                    class="site-button btn-block radius-no">Subscribe Now
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            <div class="widget widget_gallery gallery-grid-4">
                                <h6 class="widget-title style-1">Our services</h6>
                                <ul>
                                    {% for blog in blog %}
                                    <li>
                                        <div><a href="#" class="post-thum ' %}-overlay1 img-effect zoom-slow"><img
                                                src="{{blog.blog_image.url}}" alt=""></a></div>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>

                            <div class="widget widget_archive">
                                <h6 class="widget-title style-1">Categories List</h6>
                                <ul>
                                    {% for blog in blog %}
                                    <li><a href="#">{{blog.blog_category}}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="widget widget-project">
                                <h6 class="widget-title style-1">Our Project</h6>
                                <div class="widget-project-box owl-none owl-loaded owl-theme owl-carousel dots-style-1 owl-dots-black-full">
                                    {% for blog in blog %}
                                    <div class="item"><img src="{{blog.blog_image.url}}" alt=""/>
                                    </div>
                                    {% endfor %}

                                    <!--                                    <div class="item"><img src="{% static 'images/our-services/pic2.jpg' %}" alt=""/>-->
                                    <!--                                    </div>-->
                                    <!--                                    <div class="item"><img src="{% static 'images/our-services/pic3.jpg' %}" alt=""/>-->
                                    <!--                                    </div>-->
                                </div>
                            </div>

                            <div class="widget widget_tag_cloud radius">
                                <h6 class="widget-title style-1">Tags</h6>
                                <div class="tagcloud">
                                    <a href="#">Design</a>
                                    <a href="#">User interface</a>
                                    <a href="#">SEO</a>
                                    <a href="#">WordPress</a>
                                    <a href="#">Development</a>
                                    <a href="#">Joomla</a>
                                    <a href="#">Design</a>
                                    <a href="#">User interface</a>
                                    <a href="#">SEO</a>
                                    <a href="#">WordPress</a>
                                    <a href="#">Development</a>
                                    <a href="#">Joomla</a>
                                    <a href="#">Design</a>
                                    <a href="#">User interface</a>
                                    <a href="#">SEO</a>
                                    <a href="#">WordPress</a>
                                    <a href="#">Development</a>
                                    <a href="#">Joomla</a>
                                </div>
                            </div>
                        </aside>
                    </div>
                    <!-- Side bar END -->
                </div>
            </div>
        </div>
    </div>
    <!-- Content END-->
    <!-- scroll top button -->
    <button class="scroltop fa fa-chevron-up"></button>
</div>
{% endblock content %}

home/templates/home.html
{% extends 'index.html' %}
{% load static %}

{% block logo %}
{% for nav in image %}
{% if forloop.counter is 1 %}
<a href="{% url 'nav-bar' %}"><img src="{{nav.logo.url}}" alt=""></a>
{% endif %}
{% endfor %}
{% endblock %}